CasperBounty\TemplatesBundle\Entity\Templates:
    type: entity
    table: templates
    id:
        templateid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: templateId
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToMany:
        regexpcolumnid:
            targetEntity: CasperBounty\RegexpBundle\Entity\Regexpcolumns
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: templateid
            joinTable:
                name: templatetoregexpcolumns
                joinColumns:
                    -
                        name: templateId
                        referencedColumnName: templateId
                inverseJoinColumns:
                    -
                        name: regexpColumnId
                        referencedColumnName: regexpColumnId
            orderBy: null
        toolid:
            targetEntity: CasperBounty\ToolsBundle\Entity\Tools
            cascade: {  }
            fetch: LAZY
            mappedBy: templateid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
