mbgena_gena:
    resource: "@mbgenaGenaBundle/Resources/config/routing.yml"
    prefix:   /

homepage1:
    path:   /
    defaults:  { _controller: CasperBountyProjectsBundle:Default:index }
casper_bounty_tasks:
    resource: "@CasperBountyTasksBundle/Resources/config/routing.yml"
    prefix:   /

casper_bounty_services:
    resource: "@CasperBountyServicesBundle/Resources/config/routing.yml"
    prefix:   /

casper_bounty_scenario:
    resource: "@CasperBountyScenarioBundle/Resources/config/routing.yml"
    prefix:   /

casper_bounty_profiles:
    resource: "@CasperBountyProfilesBundle/Resources/config/routing.yml"
    prefix:   /

casper_bounty_front:
    resource: "@CasperBountyFrontBundle/Resources/config/routing.yml"
    prefix:   /

casper_bounty_conditions:
    resource: "@CasperBountyConditionsBundle/Resources/config/routing.yml"
    prefix:   /

regexp:
    resource: "@CasperBountyRegexpBundle/Resources/config/routing.yml"
    prefix:   /

tasklist:
    resource: "@CasperBountyTasklistBundle/Resources/config/routing.yml"
    prefix:   /

casper_bounty_tools:
    resource: "@CasperBountyToolsBundle/Controller/DefaultController.php"
    prefix:   /
    type: annotation

casper_bounty_templates:
    resource: "@CasperBountyTemplatesBundle/Resources/config/routing.yml"
    prefix:   /

casper_bounty_results:
    resource: "@CasperBountyResultsBundle/Controller/DefaultController.php"
    prefix:   /
    type: annotation

casper_bounty_groups:
    resource: "@CasperBountyGroupsBundle/Resources/config/routing.yml"
    prefix:   /

casper_bounty_targets:
    resource: "@CasperBountyTargetsBundle/Controller/DefaultController.php"
    prefix:
    type: annotation

casper_bounty_projects:
    resource: "@CasperBountyProjectsBundle/Resources/config/routing.yml"
    prefix:   /


