CasperBounty\ResultsBundle\Entity\Results:
    type: entity
    table: results
    indexes:
        FK_results_tasks:
            columns:
                - taskId
    id:
        resultid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: resultId
            generator:
                strategy: IDENTITY
    fields:
        result:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        taskid:
            targetEntity: CasperBounty\TasksBundle\Entity\Tasks
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                taskId:
                    referencedColumnName: taskId
            orphanRemoval: false
    lifecycleCallbacks: {  }
