CasperBounty\ProfilesBundle\Entity\Profiles:
    type: entity
    table: profiles
    indexes:
        fk_profiles_tools_1:
            columns:
                - toolId
    id:
        profileid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: profileId
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        cmd:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    manyToOne:
        toolid:
            targetEntity: CasperBounty\ToolsBundle\Entity\Tools
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                toolId:
                    referencedColumnName: toolId
            orphanRemoval: false
    manyToMany:
        taskid:
            targetEntity: CasperBounty\TasklistBundle\Entity\Tasklist
            cascade: {  }
            fetch: LAZY
            mappedBy: profileid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
