CasperBounty\ServicesBundle\Entity\Services:
    type: entity
    table: services
    indexes:
        serviceTid:
            columns:
                - targetId
        serviceId:
            columns:
                - serviceId
    id:
        serviceid:
            type: integer
            nullable: true
            options:
                unsigned: false
            id: true
            column: serviceId
            generator:
                strategy: IDENTITY
    fields:
        port:
            type: integer
            nullable: false
            options:
                unsigned: false
        state:
            type: boolean
            nullable: true
        service:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        version:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        targetid:
            targetEntity: CasperBounty\TargetsBundle\Entity\Targets
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                targetId:
                    referencedColumnName: targetId
            orphanRemoval: false
    oneToMany:
        taskid:
            targetEntity: CasperBounty\TasksBundle\Entity\Tasks
            cascade: {  }
            fetch: LAZY
            mappedBy: serviceid
    lifecycleCallbacks: {  }
