CasperBounty\ServicesBundle\Entity\Services:
    type: entity
    table: services
    indexes:
        serviceTid:
            columns:
                - targetId
    id:
        port:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        serviceid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: serviceId
        state:
            type: boolean
            nullable: true
        service:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        version:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToOne:
        targetid:
            targetEntity: CasperBounty\TargetsBundle\Entity\Targets
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                targetId:
                    referencedColumnName: targetId
            orphanRemoval: false
    lifecycleCallbacks: {  }
