CasperBounty\GroupsBundle\Entity\Groups:
    type: entity
    table: groups
    id:
        groupid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: groupId
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: ip/domain
    manyToMany:
        targetid:
            targetEntity: CasperBounty\TargetsBundle\Entity\Targets
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: groupid
            joinTable:
                name: groupstotarget
                joinColumns:
                    -
                        name: groupId
                        referencedColumnName: groupId
                inverseJoinColumns:
                    -
                        name: targetId
                        referencedColumnName: targetId
            orderBy: null
    lifecycleCallbacks: {  }
