CasperBounty\TargetsBundle\Entity\Targets:
    type: entity
    table: targets
    indexes:
        IDX_AF431E13856A684C:
            columns:
                - parentid
    id:
        targetid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: targetId
            generator:
                strategy: IDENTITY
    fields:
        host:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dateadded:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: dateAdded
        state:
            type: string
            length: 255
            nullable: true
            options:
              fixed: false
    oneToMany:
        serviceid:
          targetEntity: CasperBounty\ServicesBundle\Entity\Services
          mappedBy: targetid
    manyToOne:
        parentid:
            targetEntity: CasperBounty\TargetsBundle\Entity\Targets
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                parentid:
                    referencedColumnName: targetId
            orphanRemoval: false
    manyToMany:
        groupid:
            targetEntity: CasperBounty\GroupsBundle\Entity\Groups
            cascade: {  }
            fetch: LAZY
            mappedBy: targetid
            inversedBy: null
            joinTable: null
            orderBy: null
        ipid:
            targetEntity: Targets
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: domainid
            joinTable:
                name: ipdomainrelation
                joinColumns:
                    -
                        name: domainId
                        referencedColumnName: targetId
                inverseJoinColumns:
                    -
                        name: ipId
                        referencedColumnName: targetId
            orderBy: null
        domainid:
          targetEntity: Targets
          mappedBy: ipid
        projectid:
            targetEntity: CasperBounty\ProjectsBundle\Entity\Projects
            cascade: {  }
            fetch: LAZY
            mappedBy: targetid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }

Domain:
  type: entity
