services:
#    casper_bounty_targets.example:
#        class: CasperBounty\TargetsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  casper_bounty_targets.targetsService:
    class: CasperBounty\TargetsBundle\Service\TargetsService
    arguments: ["@doctrine.orm.entity_manager"]