CasperBounty\ProjectsBundle\Entity\Projects:
    type: entity
    table: projects
    id:
        projectid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: projectId
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToMany:
        targetid:
            targetEntity: CasperBounty\TargetsBundle\Entity\Targets
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: projectid
            joinTable:
                name: projecttargets
                joinColumns:
                    -
                        name: projectId
                        referencedColumnName: projectId
                inverseJoinColumns:
                    -
                        name: targetId
                        referencedColumnName: targetId
            orderBy: null
    lifecycleCallbacks: {  }
