CasperBounty\ScenarioBundle\Entity\Scenario:
    type: entity
    table: scenario
    id:
        scenarioid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: scenarioId
            generator:
                strategy: IDENTITY
    fields:
        scenarioname:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: scenarioName
    lifecycleCallbacks: {  }
