CasperBounty\ScenarioBundle\Entity\Scenariotoprofile:
    type: entity
    table: scenariotoprofile
    indexes:
        scid_fk:
            columns:
                - scenarioId
        pfid_fk:
            columns:
                - profileId
    id:
        scenprofid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: scenProfId
            generator:
                strategy: IDENTITY
    manyToOne:
        profileid:
            targetEntity: CasperBounty\ProfilesBundle\Entity\Profiles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                profileId:
                    referencedColumnName: profileId
            orphanRemoval: false
        scenarioid:
            targetEntity: Scenario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                scenarioId:
                    referencedColumnName: scenarioId
            orphanRemoval: false
    lifecycleCallbacks: {  }
