casper_bounty_tools_homepage:
    path:     /tools
    defaults: { _controller: CasperBountyToolsBundle:Default:index }
casper_bounty_tools_runtool:
    path:     /tools/{id}/run
    defaults: { _controller: CasperBountyToolsBundle:Default:runTool}
casper_bounty_tools_getallips:
    path:     /tools/{targetid}/getips
    defaults: { _controller: CasperBountyToolsBundle:Default:getHostsIps}
