casper_bounty_tools_homepage:
    path:     /tools
    defaults: { _controller: CasperBountyToolsBundle:Default:index }
casper_bounty_tools_runtool:
    path:     /tools/{id}/run
    defaults: { _controller: CasperBountyToolsBundle:Default:runTool}
casper_bounty_tools_getallips:
    path:     /tools/{targetid}/getallips
    defaults: { _controller: CasperBountyToolsBundle:Default:getHostsIps}
casper_bounty_tools_addips:
    path:     /tools/{targetid}/addips
    defaults: { _controller: CasperBountyToolsBundle:Default:addIps}
    requirements:
      targetid: \d+
      methods:  POST
