parameters:
    tool.resultsDir: 'G:\\PhpstormProjects\\CasperBounty\\results'

services:
  casper_bounty_tools.toolssrvice:
    class: CasperBounty\ToolsBundle\Service\ToolsService
    arguments: ["@doctrine.orm.entity_manager","@casper_bounty_tools.nmapservice",'%tool.resultsdir%']

  casper_bounty_tools.reconService:
    class: CasperBounty\ToolsBundle\Service\ReconService
    arguments: ["@doctrine.orm.entity_manager",%recon.aquatonePath%]

  casper_bounty_tools.nmapService:
    class: CasperBounty\ToolsBundle\Service\NmapService
    arguments: ["@doctrine.orm.entity_manager",%nmap.nmapPath%]




#    casper_bounty_projects.example:
#        class: CasperBounty\ProjectsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]