CasperBounty\RegexpBundle\Entity\Regexpcolumns:
    type: entity
    table: regexpcolumns
    indexes:
        fk_regexpColumns_regexpResult_1:
            columns:
                - regexpResultId
    id:
        regexpcolumnid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: regexpColumnId
    fields:
        columnname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: columnName
    oneToOne:
        regexpresultid:
            targetEntity: Regexpresult
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                regexpResultId:
                    referencedColumnName: regexpResultId
            orphanRemoval: false
    manyToMany:
        templateid:
            targetEntity: Templates
            cascade: {  }
            fetch: LAZY
            mappedBy: regexpcolumnid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
