CasperBounty\RegexpBundle\Entity\Regexp:
    type: entity
    table: regexp
    id:
        regexpid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: regexpId
            generator:
                strategy: IDENTITY
    fields:
        regexp:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
