services:
  casper_bounty_targets.resultsService:
    class: CasperBounty\ResultsBundle\Service\ResultsService
    arguments:
      $em: "@doctrine.orm.entity_manager"
      $targetsService: "@casper_bounty_targets.targetsservice"