CasperBounty\TasksBundle\Entity\Tasks:
    type: entity
    table: tasks
    indexes:
        scprofidstep_fk:
            columns:
                - profileId
        taridstep_fk:
            columns:
                - targetId
        FK_tasks_scenario:
            columns:
                - scenarioId
        fk_tasks_serviceid:
            columns:
                - serviceId
    id:
        taskid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: taskId
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: boolean
            nullable: false
        output:
            type: string
            nullable: true
            length: 1024
            options:
                fixed: false
        timestart:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: timeStart
        timeend:
            type: datetime
            nullable: true
            column: timeEnd
    manyToOne:
        profileid:
            targetEntity: CasperBounty\ProfilesBundle\Entity\Profiles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                profileId:
                    referencedColumnName: profileId
            orphanRemoval: false
        scenarioid:
            targetEntity: CasperBounty\ScenarioBundle\Entity\Scenario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                scenarioId:
                    referencedColumnName: scenarioId
            orphanRemoval: false
        targetid:
            targetEntity: CasperBounty\TargetsBundle\Entity\Targets
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                targetId:
                    referencedColumnName: targetId
            orphanRemoval: false
        serviceid:
            targetEntity: CasperBounty\ServicesBundle\Entity\Services
            inversedBy: taskid
            joinColumns:
                serviceid:
                    referencedColumnName: serviceId

    lifecycleCallbacks: {  }
