CasperBounty\ConditionsBundle\Entity\Conditions:
    type: entity
    table: conditions
    id:
        conditid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: conditId
            generator:
                strategy: IDENTITY
    fields:
        condition:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
