CasperBounty\ConditionsBundle\Entity\Conditiontores:
    type: entity
    table: conditiontores
    indexes:
        fk_conditionToRes_results_1:
            columns:
                - resultId
        fk_conditionToRes_profiles_1:
            columns:
                - profileId
        IDX_C0177027128AE9F0:
            columns:
                - conditionId
    id: {  }
    oneToOne:
        conditionid:
            targetEntity: CasperBounty\ConditionsBundle\Entity\Conditions
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                conditionId:
                    referencedColumnName: conditId
            orphanRemoval: false
        profileid:
            targetEntity: Profiles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                profileId:
                    referencedColumnName: profileId
            orphanRemoval: false
        resultid:
            targetEntity: CasperBounty\ResultsBundle\Entity\Results
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                resultId:
                    referencedColumnName: resultId
            orphanRemoval: false
    lifecycleCallbacks: {  }
